# Generated by Django 3.0.6 on 2020-09-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новых комментариях?'),
        ),
    ]
