# Generated by Django 3.0.6 on 2020-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_advuser_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='favorite_team',
            field=models.CharField(choices=[('Mercedes', 'Mercedes'), ('Ferrari', 'Ferrari'), ('Red Bull Racing', 'Red Bull Racing'), ('Racing Point', 'Racing Point'), ('Mclaren', 'Mclaren'), ('Renault', 'Renault'), ('Haas', 'Haas'), ('Alfa Tauri', 'Alfa Tauri'), ('Alfa Romeo', 'Alfa Romeo'), ('Williams', 'Williams')], default=True, max_length=20, verbose_name='Любимая команда'),
        ),
    ]
