# Generated by Django 3.0.6 on 2020-09-18 10:06

from django.db import migrations, models
import django_countries.fields
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200914_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(max_length=8, verbose_name='Дата рождения')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пилот',
                'verbose_name_plural': 'Пилоты',
            },
        ),
    ]
