# Generated by Django 3.0.6 on 2020-09-20 10:01

from django.db import migrations, models
import django_countries.fields
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('debut_in_f1', models.DateField(max_length=8, verbose_name='Дебют в Ф1')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Фото')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Действующая команда')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Действующий пилот?'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна'),
        ),
    ]
