# Generated by Django 3.0.6 on 2020-09-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трасса', 'verbose_name_plural': 'Трассы'},
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Team', verbose_name='Команда'),
        ),
    ]
