# Generated by Django 3.0.6 on 2020-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200922_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='team',
            name='debut_in_f1',
            field=models.DateField(verbose_name='Дебют в Ф1'),
        ),
        migrations.AlterField(
            model_name='track',
            name='build',
            field=models.DateField(verbose_name='Построена'),
        ),
    ]
