# Generated by Django 3.0.6 on 2020-10-05 09:24

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200923_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='best_laps',
            field=models.IntegerField(default=True, verbose_name='Кол-во лучших кругов'),
        ),
        migrations.AddField(
            model_name='driver',
            name='biography',
            field=models.TextField(default=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='driver',
            name='championship_win',
            field=models.IntegerField(default=True, verbose_name='Побед в чемпионате'),
        ),
        migrations.AddField(
            model_name='driver',
            name='podiums',
            field=models.IntegerField(default=True, verbose_name='Кол-во подиумов'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pole_position',
            field=models.IntegerField(default=True, verbose_name='Кол-во поулов'),
        ),
        migrations.AddField(
            model_name='driver',
            name='scores',
            field=models.IntegerField(default=True, verbose_name='Кол-во очков'),
        ),
        migrations.AddField(
            model_name='driver',
            name='starts',
            field=models.IntegerField(default=True, verbose_name='Кол-во стартов'),
        ),
        migrations.AddField(
            model_name='driver',
            name='wins',
            field=models.IntegerField(default=True, verbose_name='Кол-во побед'),
        ),
        migrations.AddField(
            model_name='team',
            name='best_laps',
            field=models.IntegerField(default=True, verbose_name='Кол-во лучших кругов'),
        ),
        migrations.AddField(
            model_name='team',
            name='constructors_win',
            field=models.IntegerField(default=True, verbose_name='Побед в Кубке конструкторов'),
        ),
        migrations.AddField(
            model_name='team',
            name='podiums',
            field=models.IntegerField(default=True, verbose_name='Кол-во подиумов'),
        ),
        migrations.AddField(
            model_name='team',
            name='pole_position',
            field=models.IntegerField(default=True, verbose_name='Кол-во поулов'),
        ),
        migrations.AddField(
            model_name='team',
            name='scores',
            field=models.IntegerField(default=True, verbose_name='Кол-во очков'),
        ),
        migrations.AddField(
            model_name='team',
            name='starts',
            field=models.IntegerField(default=True, verbose_name='Кол-во стартов'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_history',
            field=models.TextField(default=True, verbose_name='История команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=True, verbose_name='Кол-во побед'),
        ),
        migrations.AddField(
            model_name='track',
            name='flag',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Флаг'),
        ),
    ]
