# Generated by Django 3.0.6 on 2020-10-09 11:49

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201005_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_car_image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Фото болида'),
        ),
    ]
